#!/usr/bin/env bash

set -e

cd /var/www/laravel

# Set default environment variables if not defined
if [[ -z "$APP_ENV" ]]; then
    export APP_ENV=local
    echo -e "\e[33mENV undefined: APP_ENV,\e[0m use default $APP_ENV"
fi

if [[ -z "$DB_CONNECTION" ]]; then
    export DB_CONNECTION=sqlite
    echo -e "\e[33mENV undefined: DB_CONNECTION,\e[0m use default $DB_CONNECTION"
fi

if [[ "$DB_CONNECTION" = "sqlite" ]]; then
    touch database/database.sqlite
fi

# Install dependencies unless skipped
composer install --no-interaction
npm install
php artisan storage:link


if [[ -z "$APP_KEY" ]]; then
    msg="ENV undefined: APP_KEY"
    APP_KEY=$(php artisan key:generate --show)
    export APP_KEY
    echo -e "\e[33m${msg},\e[0m generated $APP_KEY"
fi


php artisan migrate --force


# Run dev environment
composer run dev
