#!/usr/bin/env bash

set -e

cd /var/www/laravel

echo "Running start with DUID=$DUID and DGID=$DGID"
echo "Running start with APP_ENV=$APP_ENV and DB_CONNECTION=$DB_CONNECTION"
echo "Running start with APP_KEY=$APP_KEY"
echo "Running start with user: $(whoami)"

if [[ -z "$APP_ENV" ]]; then
    export APP_ENV=local
    echo -e "\e[33mENV undefined: APP_ENV,\e[0m use default $APP_ENV"
fi

if [[ -z "$DB_CONNECTION" ]]; then
    export DB_CONNECTION=sqlite
    echo -e "\e[33mENV undefined: DB_CONNECTION,\e[0m use default $DB_CONNECTION"
fi

if [[ "$DB_CONNECTION" = "sqlite" ]]; then
    touch database/database.sqlite
fi

composer install --no-interaction
npm install

if [[ -z "$APP_KEY" ]]; then
    msg="ENV undefined: APP_KEY"
    APP_KEY=$(php artisan key:generate --show)
    export APP_KEY
    echo -e "\e[33m${msg},\e[0m generated $APP_KEY"
fi

php artisan migrate --force

composer run dev